### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by xoxloviwan** [jadolg/rocketchat_API#123]
https://github.com/jadolg/rocketchat_API/blob/46eedfc2a392021b0d668dbd576344895335c8bf/rocketchat_API/APISections/livechat.py#L21

When I run my code on python 3.5.2 and rocketchat_API 1.15.0 and requests 2.25.1 I got

```
$ python3 rc_upload.py
Traceback (most recent call last):
  File "rc_upload.py", line 2, in <module>
    from rocketchat_API.rocketchat import RocketChat
  File "/home/cacheusr/.local/lib/python3.5/site-packages/rocketchat_API/rocketchat.py", line 9, in <module>
    from rocketchat_API.APISections.livechat import RocketChatLivechat
  File "/home/cacheusr/.local/lib/python3.5/site-packages/rocketchat_API/APISections/livechat.py", line 21
    return self.call_api_get(f"livechat/users/{user_type}", kwargs=kwargs)
                                                         ^
SyntaxError: invalid syntax
```

**Comment by xoxloviwan** [comment]
I found the answer here: https://stackoverflow.com/questions/42126794/getting-an-invalid-syntax-when-trying-to-perform-string-interpolation
