### ISSUE TITLE
Having Trouble Authenticating in CentOS

### ISSUE THREAD

**Issue by tsai0009** [jadolg/rocketchat_API#70]
I am able to use this code in Windows to authenticate:

```
from rocketchat_API.rocketchat import RocketChat
rocket = RocketChat(username, password, server_url=server)
print(rocket.me().json())

```

Same code in CentOS gives these errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 305, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd063d86438>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=**'MYHOST'**, port=443): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd063d86438>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rcte.py", line 3, in <module>
    rocket = RocketChat(**'MYUSERNAME'**, **'MYPASSWORD'**, server_url=**'MYSERVERURL')**
  File "/usr/local/lib/python3.6/site-packages/rocketchat_API/rocketchat.py", line 29, in __init__
    self.login(user, password)  # skipcq: PTC-W1006
  File "/usr/local/lib/python3.6/site-packages/rocketchat_API/rocketchat.py", line 92, in login
    proxies=self.proxies)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=**'MYHOST'**, port=443): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd063d86438>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by jadolg** [comment]
Is this from your local installation or Docker/VM?
I need more details in order to be able to understand the issue.
It looks that the system running the code has no access to the Rocket.Chat server.
That's all I can say from the logs.

**Comment by tsai0009** [comment]
It's on a box that I connect via putty
